### ISSUE TITLE
#6 Sidebar

### ISSUE THREAD

**Issue by OlegZnamenskii** [KseniyaBk/html_group_8_teamwork_team_4#12]
# Задача
Сверстать:
- [x] Sidebar из 3-х статей
     
# План выполнения:
     - для заголовков использовать те же классы, что и в главном блоке , 
        добавить нижний бордер  навесив на доп.класс
     - заголовок с категориями сделать из ссылок, по наведению добавить ховер эффект.
        изменение  цвета на #ea5a4b к примеру
     - на экранах ниже 1024px Sidebar смещается либо под блок с видео, либо 
        в самый низ страницы под аудиоблок. на ваше усмотрение.

# Критерий готовности:
     - блоки не наезжают друг на друга, ничего не скрывается и не ломается при ресайзе

**Comment by KseniyaBk** [comment]
Выполнено по всем пунктам требований.

**Comment by OlegZnamenskii** [comment]
подкорректируйте на большом экране

**Comment by KseniyaBk** [comment]
Подкорректировала на большом экране
