### ISSUE TITLE
#1 Создать каркас четвёртой страницы Contact.html 

### ISSUE THREAD

**Issue by lustlee** [KseniyaBk/html_group_8_teamwork_team_4#13]
## Задача

- [ ] создать страницу contact.html
- [ ] перенести на страницу contact.html header + footer из index.html
- [ ] добавить переход на страницу home(index.html)

### Время фактическое:

**Comment by KseniyaBk** [comment]
Добавила страницу contact.html
В разметку включила header + footer + promo.
Добавила ссылку (index.html).
Фактическое время 
30 минут
