### ISSUE TITLE
#2 Промо-блок и шапку Contact главному блоку

### ISSUE THREAD

**Issue by lustlee** [KseniyaBk/html_group_8_teamwork_team_4#14]
## Задача

- [ ]  Сверстать адаптивный промо-блок, для Desktop и так же для Mobile(на глаз чтоб было аккуратно)
- [ ]  Сделать шапку для главного блока
- [ ] Шрифт как и во всех промо-блоках Bitter Bold
- [ ] Так же добавить паттерн (аналогично как и предыдущие промо-блоки, сам же паттерн лежит в папке images)
- [ ] Сам же блок должен налезать на промоблок, как в макете http://clip2net.com/s/3ItyHPI

## Зачем это нужно(мотивация)

 + ПЛЮС К командной работе 
 + ПЛЮС Практическая работа с GIT
 + ПЛЮС  100500 практики !!!

### Время по факту

**Comment by KseniyaBk** [comment]
Промо блок скопировала со страницы Blog.html 
(идентичные)
