### ISSUE TITLE
#3 Добавить блок с картой Google Map 

### ISSUE THREAD

**Issue by lustlee** [KseniyaBk/html_group_8_teamwork_team_4#15]
## Задача

Нужно сверстать блок и сделать внутри него адаптивный блок с картой от Google Maps

## Зачем это нужно
+ Чтоб любой пользователь находящийся на странице Контакты мог легко и быстро понять где находится данная компания или же фирма 
+ Мы это делаем чтоб облегчить жизнь других =) 

## Критерий готовности 

- [ ] Карта полностью должна работать
- [ ] При увеличении и так же уменьшении карта должна исправно показывать результат
- [ ]  При маленьком экране карта не должна ломаться и не должен появляться горизонтальный скролл

### Время по факту

**Comment by KseniyaBk** [comment]
Карта работает на разных экранах не рушится при уменьшении и увеличении страницы.
На маленьких экранах отображается без горизонтального скролла.
Время выполнения 20 минут.
