### ISSUE TITLE
#4 Сделать блок с формой и тайтл

### ISSUE THREAD

**Issue by lustlee** [KseniyaBk/html_group_8_teamwork_team_4#16]
## Задача

Нужно сверстать блок где будет Title и Форма

Сделать валидацию форм чтобы пользователь не смог отправлять не заполненую форму
- Так же при наведении на пункты формы должна выходить анимация (Hover эффект вполне сгодится)

Сверстать title рядом с формой (в макете увидите)

## Зачем это нужно(мотивация)

- Чтобы человек мог спокойно оставить свою заявку ( то есть мы делаем ДОБРО Х) )
- Валидация нужна для того чтобы на сервер не приходили пустые формы или же ошибки ( то есть давайте облегчим программистам жизнь, потому что скоро сами будем возможно этим заниматься)

## Критерий готовности

- [ ] Проверить чтоб ничего не ломась и не появлялся горизонтальный скролл!
- [x] В форме она не должна пускать нас при не заполненном поле

Время по плану 
Время по факту

**Comment by OlegZnamenskii** [comment]
валидация на высшем уровне , ховер эффект выполнен. 

время по плану 4 часа 
время по факту 4 часа

**Comment by OlegZnamenskii** [comment]
есть мелкие недочеты, на большом экране если задать паддинги инпутам , появляется бордер вокруг плэйсхолдера . ищу причину
