### ISSUE TITLE
Блок портфолио Portfolio

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#18]
## Задача

Сверстать адаптивную галерею 3й страницы portfolio.html.
Добавить контент согласно макету.

http://prntscr.com/eltv91

## Описание
Сверстать адаптивный модульный блок 3й страницы проекта. (portfolio.psd)
Принцип верстки должен повторять  общие свойства главной страницы home.html блока галереи. 
Общий принцып написания блока не должен отличатся от предыдущих страниц проекта стилем написания и названиями классов.
Верстка блока должна повторять все тэги отвечающие требованиям макета(см. ниже).

## Мотивация

Визуально блок должен выглядеть  увеличенной копией с дополнительным контентом  блока главной страницы.

## План выполнения:
Сверстать или перенести ссылки в точности повторяющие  ссылки блока галереи http://prntscr.com/eltyyk

При нажатии активная ссылка должна подсвечиваться как на главной странице сайта(index.html)
Без ховер-эффекта.
Добавить контент изображений галереи  из макета portfolio.psd
http://prntscr.com/elu0q5
12 изображений

Анимировать изображения в точности повторяющие анимацию главной страницы (index.html) используя скрипт jquery.filterizr.js .
Анимированные блоки работают при нажатии на кнопку ссылки расположенную выше.
Должен срабатывать фильтр содержимого контента.
Принцип фильтрации повторить как на главной страницы данного проекта.
https://kseniyabk.github.io/html_group_8_teamwork_team_4/

Ховер-эффект при наведении на изображения
http://prntscr.com/elu22i
в точности повторять эффект блока главной страницы (index.html).

## Критерий готовности :
Блоки идентично расположены анимируются и фильтруются по примеру блока галлереи главной страницы проекта (index.html).
Блок модульный - можно передвинуть на любую другую страницу этого проекта с условием что ничего не рушится и не ломается.
Блок адаптивный не появляется горизонтальный скролл при просмотре на маленьких экранах до 320 пикселей.
Блок при масштабировании и переключении не ломается и изображения не наезжают на друг друга.
Соблюдена визуальная точность с макетом.
При наведении на картинки появляется блок с текстом.
http://prntscr.com/elu3xp
Анимация работает при просмотре на экранах любого размера.

## Время выполнения:
4 часа.
## Фактическое время

**Comment by OlegZnamenskii** [comment]
задача выполнена не на пп . что будем решать с бутстрапом ?

**Comment by OlegZnamenskii** [comment]
> При нажатии активная ссылка должна подсвечиваться как на главной странице сайта(index.html)
Без ховер-эффекта.

хотелось бы обсудить этот момент ? в макете есть ховер . как быть ?
