### ISSUE TITLE
header

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#2]
# Задача
#
Сверстать адаптивное меню. При просмотре на маленьких экранах меню сворачивается в "меню-гамбургер" (всплывающее меню), для удобного просмотра пользователем (для мобильных устройств).
Пример:
http://prntscr.com/ehz6wm
При наведении, ссылки меняют цвет (согласно макету).  
http://prntscr.com/ei0cy7

### Teaser - верхняя часть хэдера
# 
Залить блок узором- fill patter _(темная часть header c pattern). 
кликабельные соц иконки с hover-эффект.
#
### Блок с логотипом и меню навигации по сайту (menu-nav).
#
Логотип можно реализовать шрифтом используя нестандартный шрифт.
В данном блоке необходимо расположить логотип и меню навигации по сайту. Меню должно быть выполнено с учетом адаптивности нескольких девайсов (максимально читабельно и доступно для пользователя). Для мобильных версий сайта (от 500px до 320px) необходимо сделать выпадающее меню (при наведении). 
Данный блок должен содержать перечень всех основных страниц. Меню должно располагаться справа на сайте и должно состоять из следующих элементов:
- **Home;
- Blog;
- Portfolio;
- Contact;**
При наведении на элементы меню текст элемента должен меняться согласно макету PSD.
## Критерий готовности:
Меню расположено согласно макету вверху и абсолютно совпадает с макетом.
Протестировать кроссбраузерность (Chrom, FireFox, Edge, Safari).
На мобильных устройства с разрешением от 320 px не должен появляться горизонтальный скролл.
## Время по плану:
3ч
Время по факту:

**Comment by lustlee** [comment]
Так сделал Header на Mobile First, Hamburger Menu тоже есть и так же сделал на Desktop версию
Время по факту: 1 час 30минут
