### ISSUE TITLE
Promo-slider

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#3]
# Реализация блока Promo-slider
## **Задача**
Сверстать адаптивный слайдер (при просмотре на мобильных устройствах от 320px до 500px)  с анимацией Slick на основе плагина JQuery:
-http://kenwheeler.github.io/slick/
Абсолютное совпадение с макетом.
http://prntscr.com/ei72fc
## **План выполнения:**
Все скрипты JS вынесены в отдельный файл.
**Слайдер** должен содержать 10 изображений с превью блоком. Переключение изображений должно осуществляться при помощи кнопок (пример: http://prntscr.com/ei732g), а так же при нажатии на изображение превью.
В html разметке  необходимо заполнить атрибуты img -  alt, а так же прописаны width и height размеры для более комфортной загрузки страницы сайта.
Текстовое описание каждого изображения слайдера рекомендовано расположить  position absolut c привязкой к promo-block, а так же для читабельности текста сделать бэкграунд rgba (0,0,0,0.75)б как на макете. http://prntscr.com/ei751w

**Блок превью** http://prntscr.com/ei765h
Залить узором блок-превью. Активный блок при нажатии должен выделяться http://prntscr.com/ei784j
Блок должен содержать 10 блоков миниатюр.
http://prntscr.com/ei797x
Необходимо чтобы на экранах мобильных устройств блок-превью выглядел привлекательно.

## **Критерий готовности:**
Блок адаптивный не должен появляться горизонтальный скролл до 320px. 
Анимация блока должна работать при нажатии на кнопки прокрутки или  кнопки навигации.
Блок выровнен по макету.
Протестировать на кроссбраузерность Opera, IE +10, Мozilla, Google Chrome, и Safari.
## **Время по плану** 
4 часа

**Comment by OlegZnamenskii** [comment]
выполнено на 80%+, нужны картинки

**Comment by OlegZnamenskii** [comment]
вообщем, все готово, кроме как медиа... после галереи займусь. кстати , слайдер заточен под 320 пикалей, а сетка у нас от 360 норм работает . уточните

**Comment by OlegZnamenskii** [comment]
исправил проблемку справа в превью слайдере , и поправил высоту . пока не пп

**Comment by OlegZnamenskii** [comment]
отредактировал на 320-1024 px . нужно придумать кастыль для правого края в превью
