### ISSUE TITLE
Статьи

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#4]
## Задача:
Сверстать адаптивные 3 колонки со статьями. При просмотре на маленьких экранах до 320px статьи удобный читабельный шрифт. 
## План выполнения:
- верстка колонок используя технологию-flex,
- вставить бэкграундом  слева иконки,
- текст заголовков не кликабелен 
- применить нестандартные шрифты
#
## Критерий готовности
На маленьких экранах не появляется горизонтального скролла.
На расширениях минимум 320 пикселей и выше не должен появляться скролл,
проверка на валидность.
Протестировать кроссбраузерность (Chrom, FireFox, Edge, Safari).

## Время по плану:
4 часа
Время по факту:

**Comment by lustlee** [comment]
Добавил блок статьи
сверстать адаптивные колонки с анимацией -- сделал всё кроме анимации(в процессе)

верстка колонок используя технологию-flex. ----  Сделано!!!!
вставить бэкграундом слева иконки ----- Сделано!!!
текст не кликабелен  ------ Сделано!!!
применить нестандартные шрифты ---- Сделано!!!!!
добавить анимацию при скролле ----- В процессе
