### ISSUE TITLE
Галлерея

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#5]
# Задача
Сверстать адаптивный блок галлерею с hover-effect при наведении на изображение и JS анимацией поиск по  фильтрам. Для сортировки изображений по функциональности.
По макету:
http://prntscr.com/ei7st1
#
## План выполнения:
Адаптивная верстка галереи с 8 изображениями.
http://prntscr.com/ei7sn3  
В html разметке необходимо заполнить атрибуты img - alt, а так же прописаны width и height размеры для более комфортной загрузки страницы сайта.
Добавить анимацию JS фильтров Filterizr  - https://github.com/giotiskl/Filterizr
 плагин jQuery, который сортирует, перемешивает и применяет потрясающие фильтры для галереями, используя переходы CSS3 и hover-эффекты с описанием, каждого изображения.
http://prntscr.com/ei7zqj
Добавить hover-эффект для кнопок которые сортируют элементы галереи.
#
## Критерий готовности
На маленьких экранах (до 320px) не появляется скролл и работает анимация.
Протестировать кроссбраузерность (Chrom, FireFox, Edge, Safari).
На мобильных устройствах блок выглядит приемлемо и аккуратно.
#
## Время по плану:
4 часа
Время по факту:

**Comment by OlegZnamenskii** [comment]
по галерее. готово все , но сделано на бутстрапе . медиазапросы запилил уже под все разрешения, остается пп на 1024 пикалях сделать. жду когда Рамазан запушит 
вопрос, кто сможет на флексы переделать и стоит ли ?

**Comment by OlegZnamenskii** [comment]
запушил, нужно поправить некоторые моменты .

**Comment by OlegZnamenskii** [comment]
Говорил с Гилани, он сказал что пп будут смотреть на большом экране . буду подгонять пп под него
