### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by KseniyaBk** [KseniyaBk/html_group_8_teamwork_team_4#6]
## Задача:
Сверстать адаптивный footer (подвал). При просмотре на маленьких экранах верстка не ломается и колонки с контентом должны располагаться по порядку . 
http://prntscr.com/ei864w
## **План выполнения:**

- Футер залить паттерном по макету
- блок ссылок-новостей расположить слева и сделать кликабельными поставить заглушки (#).
- описание ивента - Event description средняя колонка футера расположить строго по центру.
- Блок социальных иконок - сделать кнопки соц иконок кликабельными расположить блок справа.

## Критерий готовности:
При масштабировании и просмотре на маленьких экранах не появляется горизонтальный скролл. 
Абсолютное совпадение с макетом.
Проверка на валидность.
Протестировать кроссбраузерность (Chrom, FireFox, Edge, Safari).
## Время по плану:
4 часа.
Время фактическое:

**Comment by lustlee** [comment]
заливка паттерном --  Патерн есть!
блок ссылок-новостей ---  Тоже есть!
описание ивента - Event description --- Сделал! есть!
block-social-media ----  Тоже есть!!
Критерий готовности:

при масштабировании не появляется горизонтальный скролл --- Скролла нет!
абсолютное совпадение с макетом ----  В процессе!!!

Время по плану:

4 часа.
Время фактическое: 2ч часа ушло!
