### ISSUE TITLE
#2 Промо-блок и  шапку Blog главному блоку 

### ISSUE THREAD

**Issue by OlegZnamenskii** [KseniyaBk/html_group_8_teamwork_team_4#8]
# Задача
- [x] Сверстать адаптивный промо-блок , пп на полном экране. 
- [x] Сделать шапку для главного блока
      - Использовать шрифт для всей  шапки **Bitter Bold**
      - Сделать бэкграунд паттерном (имеется в папке images)
- [x] Главный блок должен налезать на промоблок, как в макете http://clip2net.com/s/3Imkdkq

**Comment by KseniyaBk** [comment]
Выполнено по всем пунктам требований.
